spring:
  h2:
    console:
      enabled: true
      path: /h2
    datasource:
      url: jdbc:h2:file:~/test
      username: sa
      password: sa
      driverClassName: org.h2.Driver
  activemq:
    broker-url: tcp://Javafsdnh249:61616
    password: admin
    user: admin
  application:
    name: activemq-sender
server:
  port: 8081